### ISSUE TITLE
Modelo AccountRisk

### ISSUE THREAD

**Issue by kelvinlemus** [keviper-techlatam/rupertx301#1]
se debe guardar los risk que tiene una cuenta en una tabla aparte

**Comment by keviper-techlatam** [comment]
Si asi es que esta en el diagrama pero recuerda que lo ultimo que me digiste que lo manejara como una tabla de uno a muchos, pero no hay problema, manana creo la tabla Risk y creo la relacion

**Comment by keviper-techlatam** [comment]
Subi los cambios, con la nueva relacion Account Risk Many to Many
