### ISSUE TITLE
Integrar postgresql y mongodb 

### ISSUE THREAD

**Issue by kelvinlemus** [keviper-techlatam/rupertx301#3]

**Comment by keviper-techlatam** [comment]
Ok, ahorita esta fincionando con Sqlite, voy a cambiarlo a PostgreSQL

**Comment by keviper-techlatam** [comment]
En el commit `40557d09d439e849e277d30fb5abf6c3cdccf54f` ya se relacionan las notificaiones NoSQL con los usuarion en SQL, solo queda configurar PostgreSQL para completar el issue
